// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vqmbywcuuzrpxfwsbxft.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZxbWJ5d2N1dXpycHhmd3NieGZ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU3NTYyNTQsImV4cCI6MjA2MTMzMjI1NH0.R0YnfJ8RVOQRwn8JGROfTm9yB6pH-VZpiNsS4bS412Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);